version: "3.8"

services: #def des services (containers)
  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    restart: always #redemarrage auto si crash
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inception
    env_file:
      - .env
    secrets:
      - db_password
      - db_root_password

  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    restart: always
    env_file: #docker injecte autoT tout variable(pas mdp)
      - .env
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception
    secrets: #pas mdp dans .env ou Dockerfile
      - db_password
      - credentials
    depends_on: #evite WD demarre sans mariadb
      - mariadb


  nginx:
    build: ./requirements/nginx
    container_name: nginx
    restart: always
    env_file: #docker injecte autoT tout variable(pas mdp)
      - .env
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception
    ports: #seul avec port(sujet)
      - "443:443"
    depends_on: #evite NGINX demarre sans WP
      - wordpress



networks: #def des reseaux Docker
  inception:
    driver: bridge #reseau interne Docker

volumes: #def des volumes Docker
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      device: /home/vboxuser/data/mariadb #chemin sur VM ou donnes stockees
      o: bind

  wordpress:
    driver: local
    driver_opts:
      type: none
      device: /home/vboxuser/data/wordpress
      o: bind

secrets:
  db_password:
    file : ../secrets/db_password.txt
  credentials:
    file: ../secrets/credentials.txt
  db_root_password:
    file: ../secrets/db_root_password.txt
